### ISSUE TITLE
Load secrets in GH Actions workflows using 1Password Service Accounts action

### ISSUE THREAD

**Issue by mylesagray** [kharms-dev/discord-power-bot#10]
https://developer.1password.com/docs/connect/github-actions/

(Seems to be on the beta train only) https://app-updates.agilebits.com/product_history/CLI2#v2080005

Example workflow (for macOS):

```yaml
name: Playground
on:
  workflow_dispatch: {}
env:
  OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
jobs:
  ship:
    runs-on: macos-12
    steps:
      - name: Install 1Password CLI
        run: |
          curl https://cache.agilebits.com/dist/1P/op2/pkg/v2.8.0-beta.05/op_apple_universal_v2.8.0-beta.05.pkg --output op_cli.pkg
          sudo installer -pkg op_cli.pkg -target ~
      - name: Read Field from 1Password
        run: op read "op://GitHub Actions/Bolognese Secret Ingredient/notesPlain"
```
